export const ADD_PIECE_IN_WAR_ROOM_SUCCESS = "ADD_PIECE_IN_WAR_ROOM_SUCCESS";
export const UPDATE_PIECE_IN_WAR_ROOM_SUCCESS = "UPDATE_PIECE_IN_WAR_ROOM_SUCCESS";

export const REMOVE_PIECE_FROM_MAP_SUCCESS = "REMOVE_PIECE_FROM_MAP_SUCCESS";

export const UPDATE_DROP_LOCATION_SUCCESS = "UPDATE_DROP_LOCATION_SUCCESS";

export const UPDATE_DROP_REVEAL_COMBAT_SUCCESS = "UPDATE_DROP_REVEAL_COMBAT_SUCCESS";
export const RESET_COMBAT_SUCCESS = "RESET_COMBAT_SUCCESS";

export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const NEW_GAME = "NEW_GAME";
export const NEW_GAME_SUCCESS = "NEW_GAME_SUCCESS";

export const CLEAR_REDUX_STATE = "CLEAR_REDUX_STATE";
