export const ADD_PIECE_IN_WAR_ROOM_SUCCESS = "ADD_PIECE_IN_WAR_ROOM_SUCCESS";
export const UPDATE_PIECE_IN_WAR_ROOM_SUCCESS = "UPDATE_PIECE_IN_WAR_ROOM_SUCCESS";

export const REMOVE_PIECE_FROM_MAP_SUCCESS = "REMOVE_PIECE_FROM_MAP_SUCCESS";

export const UPDATE_DROP_LOCATION_SUCCESS = "UPDATE_DROP_LOCATION_SUCCESS";

export const CLEAR_REDUX_STATE = "CLEAR_REDUX_STATE";
