// COMMON
export const UPDATE_WAR_ROOM = "UPDATE_WAR_ROOM";
export const UPDATE_WAR_ROOM_SUCCESS = "UPDATE_WAR_ROOM_SUCCESS";
export const UPDATE_WAR_ROOM_ERROR = "UPDATE_WAR_ROOM_ERROR";

export const CLEAR_REDUX_STATE = "CLEAR_REDUX_STATE";
